// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackCell.Api.Data;

#nullable disable

namespace TrackCell.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackCell.Api.Models.OperationDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("OpNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("op_number");

                    b.HasKey("Id")
                        .HasName("pk_operation_definitions");

                    b.ToTable("operation_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Machining",
                            OpNumber = "OP-10"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sub-Assembly",
                            OpNumber = "OP-20"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Primary Assembly",
                            OpNumber = "OP-30"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Testing and QA",
                            OpNumber = "OP-40"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Packaging",
                            OpNumber = "OP-50"
                        });
                });

            modelBuilder.Entity("TrackCell.Api.Models.OperationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action_level");

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("badge_number");

                    b.Property<string>("OpNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("op_number");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_number");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_operation_histories");

                    b.ToTable("operation_histories", (string)null);
                });

            modelBuilder.Entity("TrackCell.Api.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("badge_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_operators");

                    b.ToTable("operators", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeNumber = "EMP-1001",
                            Name = "Alice Smith"
                        },
                        new
                        {
                            Id = 2,
                            BadgeNumber = "EMP-1002",
                            Name = "Bob Johnson"
                        },
                        new
                        {
                            Id = 3,
                            BadgeNumber = "EMP-1003",
                            Name = "Charlie Brown"
                        },
                        new
                        {
                            Id = 4,
                            BadgeNumber = "EMP-1004",
                            Name = "Diana Prince"
                        });
                });

            modelBuilder.Entity("TrackCell.Api.Models.PartDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_number");

                    b.HasKey("Id")
                        .HasName("pk_part_definitions");

                    b.ToTable("part_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Chassis Assembly",
                            PartNumber = "PRT-001X"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Engine Block",
                            PartNumber = "PRT-002Y"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Transmission Unit",
                            PartNumber = "PRT-003Z"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Wiring Harness",
                            PartNumber = "PRT-004A"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
