// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackCell.Infrastructure.Persistence;

#nullable disable

namespace TrackCell.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516200000_ConsolidateOperatorsIntoUsers")]
    partial class ConsolidateOperatorsIntoUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackCell.Domain.Entities.ImageZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Height").HasColumnType("double precision").HasColumnName("height");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("PartImageId").HasColumnType("integer").HasColumnName("part_image_id");

                    b.Property<double>("Width").HasColumnType("double precision").HasColumnName("width");

                    b.Property<double>("X").HasColumnType("double precision").HasColumnName("x");

                    b.Property<double>("Y").HasColumnType("double precision").HasColumnName("y");

                    b.HasKey("Id").HasName("pk_image_zones");

                    b.HasIndex("PartImageId").HasDatabaseName("ix_image_zones_part_image_id");

                    b.ToTable("image_zones", (string)null);
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.ImageZoneNonConformance", b =>
                {
                    b.Property<int>("ImageZoneId").HasColumnType("integer").HasColumnName("image_zone_id");

                    b.Property<int>("NonConformanceId").HasColumnType("integer").HasColumnName("non_conformance_id");

                    b.HasKey("ImageZoneId", "NonConformanceId").HasName("pk_image_zone_non_conformances");

                    b.HasIndex("NonConformanceId").HasDatabaseName("ix_image_zone_non_conformances_non_conformance_id");

                    b.ToTable("image_zone_non_conformances", (string)null);
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.InspectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageZoneId").HasColumnType("integer").HasColumnName("image_zone_id");

                    b.Property<DateTime>("InspectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inspected_at");

                    b.Property<int>("NonConformanceId").HasColumnType("integer").HasColumnName("non_conformance_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("PartImageId").HasColumnType("integer").HasColumnName("part_image_id");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.HasKey("Id").HasName("pk_inspection_results");

                    b.HasIndex("ImageZoneId").HasDatabaseName("ix_inspection_results_image_zone_id");

                    b.HasIndex("NonConformanceId").HasDatabaseName("ix_inspection_results_non_conformance_id");

                    b.HasIndex("PartImageId").HasDatabaseName("ix_inspection_results_part_image_id");

                    b.ToTable("inspection_results", (string)null);
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.NonConformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.HasKey("Id").HasName("pk_non_conformances");

                    b.HasIndex("Code").IsUnique().HasDatabaseName("ix_non_conformances_code");

                    b.ToTable("non_conformances", (string)null);

                    b.HasData(
                        new { Id = 1, Code = "NC-SCR", Description = "Scratch" },
                        new { Id = 2, Code = "NC-DNT", Description = "Dent" },
                        new { Id = 3, Code = "NC-MIS", Description = "Missing Fastener" },
                        new { Id = 4, Code = "NC-ALN", Description = "Misalignment" },
                        new { Id = 5, Code = "NC-COR", Description = "Corrosion" },
                        new { Id = 6, Code = "NC-CLR", Description = "Wrong Color" },
                        new { Id = 7, Code = "NC-CRK", Description = "Crack" },
                        new { Id = 8, Code = "NC-BRR", Description = "Burr / Sharp Edge" });
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.OperationDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("OpNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("op_number");

                    b.HasKey("Id").HasName("pk_operation_definitions");

                    b.ToTable("operation_definitions", (string)null);

                    b.HasData(
                        new { Id = 1, Description = "Machining", OpNumber = "OP-10" },
                        new { Id = 2, Description = "Sub-Assembly", OpNumber = "OP-20" },
                        new { Id = 3, Description = "Primary Assembly", OpNumber = "OP-30" },
                        new { Id = 4, Description = "Testing and QA", OpNumber = "OP-40" },
                        new { Id = 5, Description = "Packaging", OpNumber = "OP-50" });
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.OperationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action_level");

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("badge_number");

                    b.Property<string>("OpNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("op_number");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_number");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id").HasName("pk_operation_histories");

                    b.ToTable("operation_histories", (string)null);
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.PartDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_number");

                    b.HasKey("Id").HasName("pk_part_definitions");

                    b.ToTable("part_definitions", (string)null);

                    b.HasData(
                        new { Id = 1, Description = "Chassis Assembly", PartNumber = "PRT-001X" },
                        new { Id = 2, Description = "Engine Block", PartNumber = "PRT-002Y" },
                        new { Id = 3, Description = "Transmission Unit", PartNumber = "PRT-003Z" },
                        new { Id = 4, Description = "Wiring Harness", PartNumber = "PRT-004A" });
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.PartImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("PartDefinitionId").HasColumnType("integer").HasColumnName("part_definition_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id").HasName("pk_part_images");

                    b.HasIndex("PartDefinitionId").HasDatabaseName("ix_part_images_part_definition_id");

                    b.ToTable("part_images", (string)null);
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.ServerMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AvailableDiskBytes").HasColumnType("bigint").HasColumnName("available_disk_bytes");
                    b.Property<long>("AvailableMemoryBytes").HasColumnType("bigint").HasColumnName("available_memory_bytes");
                    b.Property<double>("CpuUsagePercent").HasColumnType("double precision").HasColumnName("cpu_usage_percent");
                    b.Property<double>("DiskUsagePercent").HasColumnType("double precision").HasColumnName("disk_usage_percent");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("health_status");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("machine_name");

                    b.Property<double>("MemoryUsagePercent").HasColumnType("double precision").HasColumnName("memory_usage_percent");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<long>("TotalDiskBytes").HasColumnType("bigint").HasColumnName("total_disk_bytes");
                    b.Property<long>("TotalMemoryBytes").HasColumnType("bigint").HasColumnName("total_memory_bytes");
                    b.Property<long>("UptimeSeconds").HasColumnType("bigint").HasColumnName("uptime_seconds");

                    b.HasKey("Id").HasName("pk_server_metrics");

                    b.HasIndex("MachineName", "Timestamp").HasDatabaseName("ix_server_metrics_machine_name_timestamp");

                    b.ToTable("server_metrics", (string)null);
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("badge_number");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("WindowsAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("windows_account");

                    b.HasKey("Id").HasName("pk_users");

                    b.HasIndex("WindowsAccount").IsUnique().HasDatabaseName("ix_users_windows_account");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new { Id = 1, BadgeNumber = "EMP-1001", DisplayName = "Alice Smith",   Role = "Operator",   WindowsAccount = "DOMAIN\\asmith" },
                        new { Id = 2, BadgeNumber = "EMP-1002", DisplayName = "Bob Johnson",   Role = "Operator",   WindowsAccount = "DOMAIN\\bjohnson" },
                        new { Id = 3, BadgeNumber = "EMP-1003", DisplayName = "Charlie Brown", Role = "Supervisor", WindowsAccount = "DOMAIN\\cbrown" },
                        new { Id = 4, BadgeNumber = "EMP-1004", DisplayName = "Diana Prince",  Role = "Admin",      WindowsAccount = "DOMAIN\\dprince" },
                        new { Id = 5, BadgeNumber = "EMP-1005", DisplayName = "Eve Watson",    Role = "Inspector",  WindowsAccount = "DOMAIN\\ewatson" });
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.ImageZone", b =>
                {
                    b.HasOne("TrackCell.Domain.Entities.PartImage", "PartImage")
                        .WithMany("Zones")
                        .HasForeignKey("PartImageId")
                        .HasConstraintName("fk_image_zones_part_images_part_image_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartImage");
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.ImageZoneNonConformance", b =>
                {
                    b.HasOne("TrackCell.Domain.Entities.ImageZone", "ImageZone")
                        .WithMany("NonConformances")
                        .HasForeignKey("ImageZoneId")
                        .HasConstraintName("fk_image_zone_non_conformances_image_zones_image_zone_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackCell.Domain.Entities.NonConformance", "NonConformance")
                        .WithMany()
                        .HasForeignKey("NonConformanceId")
                        .HasConstraintName("fk_image_zone_non_conformances_non_conformances_non_conformance_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageZone");
                    b.Navigation("NonConformance");
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.InspectionResult", b =>
                {
                    b.HasOne("TrackCell.Domain.Entities.ImageZone", "ImageZone")
                        .WithMany()
                        .HasForeignKey("ImageZoneId")
                        .HasConstraintName("fk_inspection_results_image_zones_image_zone_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackCell.Domain.Entities.NonConformance", "NonConformance")
                        .WithMany()
                        .HasForeignKey("NonConformanceId")
                        .HasConstraintName("fk_inspection_results_non_conformances_non_conformance_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrackCell.Domain.Entities.PartImage", "PartImage")
                        .WithMany()
                        .HasForeignKey("PartImageId")
                        .HasConstraintName("fk_inspection_results_part_images_part_image_id")
                        .IsRequired();

                    b.Navigation("ImageZone");
                    b.Navigation("NonConformance");
                    b.Navigation("PartImage");
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.PartImage", b =>
                {
                    b.HasOne("TrackCell.Domain.Entities.PartDefinition", "PartDefinition")
                        .WithMany()
                        .HasForeignKey("PartDefinitionId")
                        .HasConstraintName("fk_part_images_part_definitions_part_definition_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartDefinition");
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.ImageZone", b =>
                {
                    b.Navigation("NonConformances");
                });

            modelBuilder.Entity("TrackCell.Domain.Entities.PartImage", b =>
                {
                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
#pragma warning restore 612, 618
        }
    }
}
